version: '3.9'

networks:
  msr_network:
    driver: bridge
    ipam:
      config:
        - subnet: 172.102.0.0/16

services:
  master:
    container_name: ${DOCKER_DOMAIN}-master-mysql
    image: ${DOCKER_DOMAIN}-master-mysql:8.0.25
    build:
      context: ./docker
      dockerfile: Dockerfile_Mysql_Master
    ports:
      - ${DOCKER_MYSQL_MASTER_PORT}:3306
    volumes:
      - ${MYSQL_SYSTEM_DIR-./mysql/master}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql/master}:/var/log/mysql
    networks:
      msr_network:
        ipv4_address: 172.102.0.10
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT}
      MYSQL_DATABASE: ${DOCKER_MYSQL_NAME}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASS}

  slave-1:
    container_name: ${DOCKER_DOMAIN}-slave-1-mysql
    image: ${DOCKER_DOMAIN}-slave-1-mysql:8.0.25
    build:
      context: ./docker
      dockerfile: Dockerfile_Mysql_Slave1
    ports:
      - ${DOCKER_MYSQL_SLAVE1_PORT}:3306
    volumes:
      - ${MYSQL_SYSTEM_DIR-./mysql/slave/1}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql/slave/1}:/var/log/mysql
    networks:
      - msr_network
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT}
      MYSQL_DATABASE: ${DOCKER_MYSQL_NAME}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASS}

  slave-2:
    container_name: ${DOCKER_DOMAIN}-slave-2-mysql
    image: ${DOCKER_DOMAIN}-slave-2-mysql:8.0.25
    build:
      context: ./docker
      dockerfile: Dockerfile_Mysql_Slave2
    ports:
      - ${DOCKER_MYSQL_SLAVE2_PORT}:3306
    volumes:
      - ${MYSQL_SYSTEM_DIR-./mysql/slave/2}:/var/lib/mysql
      - ${MYSQL_LOG_DIR-./logs/mysql/slave/2}:/var/log/mysql
    networks:
      - msr_network
    command: --default-authentication-plugin=mysql_native_password
    environment:
      MYSQL_ROOT_PASSWORD: ${DOCKER_MYSQL_ROOT}
      MYSQL_DATABASE: ${DOCKER_MYSQL_NAME}
      MYSQL_USER: ${DOCKER_MYSQL_USER}
      MYSQL_PASSWORD: ${DOCKER_MYSQL_PASS}

  phpmyadmin-master:
    container_name: ${DOCKER_DOMAIN}-master-phpmyadmin
    image: ${DOCKER_DOMAIN}-master-phpmyadmin:5.2.2
    build:
      context: ./docker
      dockerfile: Dockerfile_PhpMyAdmin
    ports:
      - ${DOCKER_PHPMYADMIN_MASTER_PORT}:80
    networks:
      - msr_network
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DOCKER_DOMAIN}-master-mysql
      - PAM_PORT=${DOCKER_MYSQL_MASTER_PORT}
      - PMA_USER=${DOCKER_MYSQL_USER}
      - PMA_PASSWORD=${DOCKER_MYSQL_PASS}
    depends_on:
      - master

  phpmyadmin-slave-1:
    container_name: ${DOCKER_DOMAIN}-slave-1-phpmyadmin
    image: ${DOCKER_DOMAIN}-slave-1-phpmyadmin:5.2.2
    build:
      context: ./docker
      dockerfile: Dockerfile_PhpMyAdmin
    ports:
      - ${DOCKER_PHPMYADMIN_SLAVE1_PORT}:80
    networks:
      - msr_network
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DOCKER_DOMAIN}-slave-1-mysql
      - PAM_PORT=${DOCKER_MYSQL_SLAVE1_PORT}
      - PMA_USER=${DOCKER_MYSQL_USER}
      - PMA_PASSWORD=${DOCKER_MYSQL_PASS}
    depends_on:
      - slave-1

  phpmyadmin-slave-2:
    container_name: ${DOCKER_DOMAIN}-slave-2-phpmyadmin
    image: ${DOCKER_DOMAIN}-slave-2-phpmyadmin:5.2.2
    build:
      context: ./docker
      dockerfile: Dockerfile_PhpMyAdmin
    ports:
      - ${DOCKER_PHPMYADMIN_SLAVE2_PORT}:80
    networks:
      - msr_network
    environment:
      - PMA_ARBITRARY=1
      - PMA_HOST=${DOCKER_DOMAIN}-slave-2-mysql
      - PAM_PORT=${DOCKER_MYSQL_SLAVE2_PORT}
      - PMA_USER=${DOCKER_MYSQL_USER}
      - PMA_PASSWORD=${DOCKER_MYSQL_PASS}
    depends_on:
      - slave-2
