STOP SLAVE;

CHANGE MASTER TO
  MASTER_HOST = '172.102.0.10',
  MASTER_USER = 'repl',
  MASTER_PASSWORD = 'replica_pass',
  MASTER_LOG_FILE = 'mysql-bin.000003',
  MASTER_LOG_POS  = 156;

START SLAVE;
